[versions]
kotlin = "2.1.10"
koog-agents = "0.5.4-develop-20251118-0203"
logback = "1.5.13"

[libraries]
koog-agents = { module = "ai.koog:koog-agents", version.ref = "koog-agents"}
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

[plugins]
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
